### ISSUE TITLE
Please add support for Firefox

### ISSUE THREAD

**Issue by andreicristianpetcu** [gabrielbarros/localstorage-manager#2]
Hi! Do you have any plans to support Firefox? Firefox extensions have the same format as Chrome extensions these days. https://vimeo.com/241435808 There are a few different APIs but they are mostly the same https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Browser_support_for_JavaScript_APIs

**Comment by andreicristianpetcu** [comment]
[I made a build](https://github.com/andreicristianpetcu/localstorage-manager/releases/download/2.4/unofficial_localstorage_manager-2.4-an+fx.xpi). Download actually copies to clipboard. It only works in [Firefox Nightly](https://www.mozilla.org/en-US/firefox/nightly/all/) v63 will work on [DevEdition and Beta starting November 5th](https://www.mozilla.org/en-US/firefox/developer/).

Hope @gabrielbarros can look into doing a proper fix since what I did is basically a hack :D.

**Comment by andreicristianpetcu** [comment]
I made it work in Firefox stable. [Here it is](https://github.com/andreicristianpetcu/localstorage-manager/releases/download/2.4.1/unofficial_localstorage_manager-2.4.1-an+fx.xpi)

```javascript
            iframe.onload = function() {
                var doc = this.contentDocument;
                var file = new Blob([response]);
                console.log(response);
                var a = doc.createElement('a');
                a.href = window.URL.createObjectURL(file);
                a.download = filename;
                a.style.display = 'none';
                doc.body.appendChild(a);
                window.location = 'data:text/plain;,' + response;
            };
```

**Comment by gabrielbarros** [comment]
Great! The motherfucking prompt is finally working on Firefox 63!

![img](https://user-images.githubusercontent.com/3298817/44799838-4b7bab80-ab8b-11e8-8bd1-aa4975244603.png)

I'll test it more carefully as soon as I have time. :+1:
